baseURL = "https://bingcheng.space/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "邱秉誠 (BingCheng)"
pagination.pagerSize = 3
theme = "hulga"

[params]
  # show in HTML meta tag
  author = "BingCheng"
  keywords = "Blog"
  description = "Bingcheng's blog"

  # change bulma's primary color
  primaryColor = "#0969e6"

  # use primary color everywhere, default true
  primaryEverywhere = true

  # change bulma's link color (secondary color in this theme)
  # linkColor = "#f91880"

  # subtitle on homepage
  subtitle = "Share my learning journey"

  # enable katex rendering on every post page, default false
  math = true
 
  # enable showing content summary below post title in home page, default false
  showSummary = true

  # set paginate on taxonomy term page (tags or categories), default 10
  termPaginate = 3

  # enable toc on every post page, default false
  toc = true

  # enable TOC auto collapse, default false
  autoCollapseToc = false

  # enable prefers-color-scheme:dark, default false
  darkMedia = true

  # enable user to toggle dark mode with a menu, default false
  darkToggle = true

  # enable hero section's is-bold effect, default false
  heroBold = false

  # enable hero section that looks like steam deck's home page, default false
  heroSteamDeck = false

  # enable PWA, prepare your icons and DON'T forget to modify manifest.json, default false
  pwa = true

  # disable jsdelivr cdn, default false
  noCDN = false

# for postcss-purgecss
# see https://purgecss.com/guides/hugo.html
# [build]
#   writeStats = true

[markup]
  [markup.highlight]
    noClasses = false
    
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
  [[menu.main]]
    identifier = "index"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 4

[taxonomies]
category = "categories"
tag = "tags"